name: deploy-docs
on:
  # クリックによってデプロイ
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: npm ci
        run: npm ci
      - name: npm c
        run: npm ci
      - name: git config
        run: |
          git config --global user.email "ci@kyuzan.com"
          git config --global user.name "GitHubActions"
      - run: npm run deploy
        env:
          GIT_USER: ${{ github.actor }}:${{ github.token }}
